AllCops:
  NewCops: enable

require:
  - rubocop-performance
  - rubocop-sequel

Style/Documentation:
  Enabled: false

Layout/LineLength:
  Max: 250

# Metrics Cops

Metrics/ClassLength:
  Description: 'Avoid classes longer than 250 lines of code.'
  Max: 250
  Enabled: true

Metrics/ModuleLength:
  Description: 'Avoid modules longer than 250 lines of code.'
  Max: 250
  Enabled: true

Metrics/ParameterLists:
  Description: 'Pass no more than four parameters into a method.'
  Max: 5
  Enabled: true

Metrics/MethodLength:
  Description: 'Avoid methods longer than 50 lines of code.'
  StyleGuide: '<https://github.com/bbatsov/ruby-style-guide#short-methods>'
  Max: 50
  Enabled: true
  IgnoredMethods:
    - to_s

Metrics/BlockLength:
  CountComments: false
  Max: 10
  IgnoredMethods:
    - Sequel.migration
    - create_table
    - change
    - up
    - down
    - context
    - describe
    - it
    - to_s

Metrics/AbcSize:
  IgnoredMethods:
    - to_s

Metrics/CyclomaticComplexity:
  IgnoredMethods:
    - to_s

Metrics/PerceivedComplexity:
  IgnoredMethods:
    - to_s
