# frozen_string_literal: true

# Table: account_wallets
# Columns:
#  id         | integer                     | PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY
#  account_id | integer                     | NOT NULL
#  wallet_id  | integer                     | NOT NULL
#  created_at | timestamp without time zone | NOT NULL
# Indexes:
#  account_wallets_pkey                     | PRIMARY KEY btree (id)
#  account_wallets_account_id_wallet_id_key | UNIQUE btree (account_id, wallet_id)
#  account_wallets_created_at_index         | btree (created_at)
# Foreign key constraints:
#  account_wallets_account_id_fkey | (account_id) REFERENCES accounts(id)
#  account_wallets_wallet_id_fkey  | (wallet_id) REFERENCES wallets(id)

class AccountWallet < Sequel::Model
  many_to_one :account
  many_to_one :wallet
end
