# frozen_string_literal: true

# Table: accounts
# Columns:
#  id                  | integer                     | PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY
#  portfolio_id        | integer                     | NOT NULL
#  platform_id         | integer                     | NOT NULL
#  platform_account_id | text                        |
#  name                | character varying(255)      | NOT NULL
#  accounting_method   | accounting_method           | NOT NULL DEFAULT 'fifo'::accounting_method
#  started_on          | date                        | NOT NULL
#  created_at          | timestamp without time zone | NOT NULL
#  updated_at          | timestamp without time zone | NOT NULL
# Indexes:
#  accounts_pkey                                               | PRIMARY KEY btree (id)
#  accounts_created_at_index                                   | btree (created_at)
#  accounts_portfolio_id_platform_id_index                     | btree (portfolio_id, platform_id)
#  accounts_portfolio_id_platform_id_name_index                | btree (portfolio_id, platform_id, name)
#  accounts_portfolio_id_platform_id_platform_account_id_index | btree (portfolio_id, platform_id, platform_account_id)
# Foreign key constraints:
#  accounts_platform_id_fkey  | (platform_id) REFERENCES platforms(id)
#  accounts_portfolio_id_fkey | (portfolio_id) REFERENCES portfolios(id)
# Referenced By:
#  account_wallets | account_wallets_account_id_fkey | (account_id) REFERENCES accounts(id)
#  acquisitions    | acquisitions_account_id_fkey    | (account_id) REFERENCES accounts(id)
#  assets          | assets_account_id_fkey          | (account_id) REFERENCES accounts(id)
#  disposals       | disposals_account_id_fkey       | (account_id) REFERENCES accounts(id)
#  transactions    | transactions_account_id_fkey    | (account_id) REFERENCES accounts(id)

class Account < Sequel::Model
  many_to_one :portfolio
  many_to_one :platform
  one_to_many :account_wallets
  one_to_many :assets
  one_to_many :acquisitions
  one_to_many :transactions
  one_to_many :unprocessed_transactions, class: :Transaction do |ds|
    ds.where(processed: false).order(:completed_at)
  end

  def unprocess_transactions!
    DB[:transactions].where(account_id: id).update(processed: false)
  end

  def reset_transactions!
    reset_assets!
    DB[:transactions].where(account_id: id).delete
  end

  def reset_assets!
    DB[:disposals].where(account_id: id).delete
    DB[:assets].where(account_id: id).delete
    DB[:acquisitions].where(account_id: id).delete
  end
end
