# frozen_string_literal: true

# Table: acquisitions
# Columns:
#  id                  | integer                     | PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY
#  transaction_id      | integer                     |
#  account_id          | integer                     | NOT NULL
#  currency_id         | integer                     | NOT NULL
#  amount              | numeric                     | NOT NULL
#  cost_currency_id    | integer                     |
#  cost_amount         | numeric                     |
#  average_cost_amount | numeric                     |
#  has_cost            | boolean                     | NOT NULL DEFAULT false
#  type                | acquisition_type            | NOT NULL
#  acquired_at         | timestamp without time zone | NOT NULL
#  created_at          | timestamp without time zone | NOT NULL
# Indexes:
#  acquisitions_pkey                                               | PRIMARY KEY btree (id)
#  acquisitions_transaction_id_key                                 | UNIQUE btree (transaction_id)
#  acquisitions_account_id_acquired_at_index                       | btree (account_id, acquired_at)
#  acquisitions_account_id_currency_id_acquired_at_index           | btree (account_id, currency_id, acquired_at)
#  acquisitions_account_id_currency_id_type_acquired_at_index      | btree (account_id, currency_id, type, acquired_at)
#  acquisitions_account_id_has_cost_acquired_at_index              | btree (account_id, has_cost, acquired_at)
#  acquisitions_account_id_has_cost_currency_id_acquired_at_index  | btree (account_id, has_cost, currency_id, acquired_at)
#  acquisitions_account_id_has_cost_currency_id_type_acquired_at_i | btree (account_id, has_cost, currency_id, type, acquired_at)
#  acquisitions_account_id_type_acquired_at_index                  | btree (account_id, type, acquired_at)
#  acquisitions_created_at_account_id_index                        | btree (created_at, account_id)
# Foreign key constraints:
#  acquisitions_account_id_fkey       | (account_id) REFERENCES accounts(id)
#  acquisitions_cost_currency_id_fkey | (cost_currency_id) REFERENCES currencies(id)
#  acquisitions_currency_id_fkey      | (currency_id) REFERENCES currencies(id)
# Referenced By:
#  assets    | assets_acquisition_id_fkey    | (acquisition_id) REFERENCES acquisitions(id)
#  disposals | disposals_acquisition_id_fkey | (acquisition_id) REFERENCES acquisitions(id)

class Acquisition < Sequel::Model
  many_to_one :account
  many_to_one :currency
  many_to_one :cost_currency, class: :Currency
  many_to_one :transaction

  def before_save
    set_average_cost_amount
    super
  end

  def after_create
    create_asset
    super
  end

  def to_s
    output = +''
    col_width = 25
    symbol_width = 8
    if id
      id_col = id.to_s.rjust(15)
      output << id_col
      output << ' | '
    end

    account_col = account.name.rjust(15)
    output << account_col
    output << ' | '

    type_col = type.rjust(12)
    currency_symbol = currency.symbol.ljust(symbol_width)
    currency_col = format("%20.10f #{currency_symbol}", amount)
    cost_currency_symbol = cost_currency.symbol.ljust(symbol_width)
    cost_currency_col = format("%20.10f #{cost_currency_symbol}", cost_amount)
    avg_currency_symbol = "#{cost_currency.symbol} / #{currency.symbol}".ljust((symbol_width * 2) - 4)
    avg_cost_currency_col = format("%20.10f #{avg_currency_symbol}", average_cost_amount)

    output << type_col
    output << " | #{currency_col.rjust(col_width)} x #{avg_cost_currency_col}"
    output << " = #{cost_currency_col.rjust(col_width)}"
    output << " | @ #{acquired_at}"
    output
  end

  private

  def create_asset
    Asset.create(
      portfolio_id: account.portfolio_id,
      acquisition: self,
      account:,
      currency:,
      amount:,
      cost_currency:,
      cost_amount:,
      average_cost_amount:,
      type:,
      acquired_at:
    )
  end

  def set_average_cost_amount
    return unless average_cost_amount.nil? && has_cost && cost_amount && amount&.positive?

    self.average_cost_amount = cost_amount / amount
  end
end
