# frozen_string_literal: true

# Table: disposals
# Columns:
#  id                      | integer                     | PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY
#  portfolio_id            | integer                     | NOT NULL
#  account_id              | integer                     | NOT NULL
#  currency_id             | integer                     | NOT NULL
#  fiat_currency_id        | integer                     | NOT NULL
#  transaction_id          | integer                     |
#  acquisition_id          | integer                     | NOT NULL
#  acquisition_type        | acquisition_type            | NOT NULL
#  type                    | disposal_type               | NOT NULL
#  capital_gains_treatment | capital_gains_treatment     | NOT NULL
#  amount                  | numeric                     | NOT NULL
#  cost_amount             | numeric                     | NOT NULL
#  sold_amount             | numeric                     | NOT NULL
#  net_amount              | numeric                     | NOT NULL
#  acquired_at             | timestamp without time zone | NOT NULL
#  disposed_at             | timestamp without time zone | NOT NULL
#  created_at              | timestamp without time zone | NOT NULL
# Indexes:
#  disposals_pkey                                                  | PRIMARY KEY btree (id)
#  disposals_acquisition_id_index                                  | btree (acquisition_id)
#  disposals_created_at_index                                      | btree (created_at)
#  disposals_portfolio_id_account_id_capital_gains_treatment_dispo | btree (portfolio_id, account_id, capital_gains_treatment, disposed_at, acquired_at)
#  disposals_portfolio_id_account_id_currency_id_disposed_at_acqui | btree (portfolio_id, account_id, currency_id, disposed_at, acquired_at)
#  disposals_portfolio_id_account_id_currency_id_type_disposed_at_ | btree (portfolio_id, account_id, currency_id, type, disposed_at, acquired_at)
#  disposals_portfolio_id_account_id_disposed_at_acquired_at_index | btree (portfolio_id, account_id, disposed_at, acquired_at)
#  disposals_portfolio_id_account_id_type_disposed_at_acquired_at_ | btree (portfolio_id, account_id, type, disposed_at, acquired_at)
#  disposals_portfolio_id_capital_gains_treatment_disposed_at_acqu | btree (portfolio_id, capital_gains_treatment, disposed_at, acquired_at)
#  disposals_portfolio_id_currency_id_disposed_at_acquired_at_inde | btree (portfolio_id, currency_id, disposed_at, acquired_at)
#  disposals_portfolio_id_currency_id_type_disposed_at_acquired_at | btree (portfolio_id, currency_id, type, disposed_at, acquired_at)
#  disposals_portfolio_id_disposed_at_acquired_at_index            | btree (portfolio_id, disposed_at, acquired_at)
#  disposals_portfolio_id_type_disposed_at_acquired_at_index       | btree (portfolio_id, type, disposed_at, acquired_at)
#  disposals_transaction_id_index                                  | btree (transaction_id)
# Foreign key constraints:
#  disposals_account_id_fkey       | (account_id) REFERENCES accounts(id)
#  disposals_acquisition_id_fkey   | (acquisition_id) REFERENCES acquisitions(id)
#  disposals_currency_id_fkey      | (currency_id) REFERENCES currencies(id)
#  disposals_fiat_currency_id_fkey | (fiat_currency_id) REFERENCES currencies(id)
#  disposals_portfolio_id_fkey     | (portfolio_id) REFERENCES portfolios(id)

class Disposal < Sequel::Model
  many_to_one :portfolio
  many_to_one :account
  many_to_one :currency
  many_to_one :fiat_currency, class: :Currency
  many_to_one :transaction
  many_to_one :acquisition

  # 366 days
  # reference: https://www.tradelogsoftware.com/resources/filing-taxes/capital-gains/
  LONG_TERM_GAIN_DAYS = 366

  def before_validation
    set_acquisition_fields
    set_net_amount
    set_captital_gains_treatment
    super
  end

  def disposed_on
    disposed_at&.to_date
  end

  def acquired_on
    acquired_at&.to_date
  end

  def to_s
    output = +''
    col_width = 10
    symbol_width = 5
    if id
      id_col = id.to_s.rjust(15)
      output << id_col
      output << ' | '
    end

    account_col = account.name.rjust(15)
    output << account_col
    output << ' | '

    type_col = type.rjust(12)
    acquisition_type_col = acquisition_type.rjust(12)

    currency_symbol = currency.symbol.ljust(symbol_width)
    fiat_symbol = fiat_currency.symbol.ljust(symbol_width)
    avg_symbol = "#{fiat_currency.symbol}/#{currency.symbol}".ljust(symbol_width * 2 + 1)

    amount_col = format("%20.10f #{currency_symbol}", amount).rjust(25)
    cost_col = format("%6.2f #{fiat_symbol}", cost_amount).rjust(col_width)
    avg_cost_col = format("(@ %6.2f #{avg_symbol})", cost_amount / amount).ljust(col_width + 4)
    sold_col = format("%9.2f #{fiat_symbol}", sold_amount).rjust(col_width)
    avg_sold_col = format("(@ %6.2f #{fiat_symbol})", sold_amount / amount).ljust(col_width + 4)
    net_col = format("%9.2f #{fiat_symbol}", net_amount).rjust(col_width)

    output << acquisition_type_col
    output << " | #{type_col}"
    output << " | #{amount_col}"
    output << " | #{sold_col} #{avg_sold_col} - #{cost_col} #{avg_cost_col} = #{net_col}"

    output << " | #{capital_gains_treatment.rjust(12)}"

    days = (disposed_on - acquired_on).to_i
    output << " | @ #{acquired_on} - #{disposed_on} = #{days} days"
    output
  end

  private

  def set_net_amount
    return unless amount && cost_amount

    self.net_amount = sold_amount - cost_amount
  end

  def set_captital_gains_treatment
    return unless acquired_at && disposed_at

    self.capital_gains_treatment = ((disposed_on - acquired_on).to_i < LONG_TERM_GAIN_DAYS ? 'short_term' : 'long_term')
  end

  def set_acquisition_fields
    return unless acquisition_id

    self.acquisition_type = acquisition.type if acquisition_type.nil? && acquisition
    self.acquired_at = acquisition.acquired_at if acquired_at.nil? && acquisition
  end
end
