# frozen_string_literal: true

# Table: platforms
# Columns:
#  id         | integer                     | PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY
#  name       | character varying(255)      | NOT NULL
#  url        | text                        |
#  created_at | timestamp without time zone | NOT NULL
#  updated_at | timestamp without time zone | NOT NULL
# Indexes:
#  platforms_pkey             | PRIMARY KEY btree (id)
#  platforms_name_index       | UNIQUE btree (name)
#  platforms_created_at_index | btree (created_at)
#  platforms_updated_at_index | btree (updated_at)
# Referenced By:
#  accounts | accounts_platform_id_fkey | (platform_id) REFERENCES platforms(id)
#  wallets  | wallets_platform_id_fkey  | (platform_id) REFERENCES platforms(id)

class Platform < Sequel::Model
  plugin :static_cache

  BY_NAME = all.each_with_object({}) do |p, h|
    h[p.name] = p
  end.freeze

  many_to_many :accounts

  def self.by_name(name)
    BY_NAME[name]
  end
end
