# frozen_string_literal: true

# Table: transferred_assets
# Columns:
#  id                          | integer                     | PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY
#  portfolio_id                | integer                     | NOT NULL
#  from_account_id             | integer                     | NOT NULL
#  to_account_id               | integer                     | NOT NULL
#  transfer_id                 | integer                     | NOT NULL
#  currency_id                 | integer                     | NOT NULL
#  cost_currency_id            | integer                     | NOT NULL
#  acquisition_id              | integer                     | NOT NULL
#  acquisition_type            | acquisition_type            | NOT NULL
#  amount                      | numeric                     | NOT NULL
#  cost_amount                 | numeric                     |
#  average_cost_amount         | numeric                     |
#  account_cost_amount         | numeric                     | DEFAULT 0
#  account_average_cost_amount | numeric                     | DEFAULT 0
#  acquired_at                 | timestamp without time zone | NOT NULL
#  account_acquired_at         | timestamp without time zone | NOT NULL
#  created_at                  | timestamp without time zone | NOT NULL
# Indexes:
#  transferred_assets_pkey                                         | PRIMARY KEY btree (id)
#  transferred_assets_acquisition_id_index                         | btree (acquisition_id)
#  transferred_assets_created_at_portfolio_id_index                | btree (created_at, portfolio_id)
#  transferred_assets_from_account_id_created_at_index             | btree (from_account_id, created_at)
#  transferred_assets_from_account_id_currency_id_created_at_index | btree (from_account_id, currency_id, created_at)
#  transferred_assets_portfolio_id_created_at_index                | btree (portfolio_id, created_at)
#  transferred_assets_portfolio_id_currency_id_created_at_index    | btree (portfolio_id, currency_id, created_at)
#  transferred_assets_to_account_id_created_at_index               | btree (to_account_id, created_at)
#  transferred_assets_to_account_id_currency_id_created_at_index   | btree (to_account_id, currency_id, created_at)
#  transferred_assets_transfer_id_index                            | btree (transfer_id)
# Foreign key constraints:
#  transferred_assets_acquisition_id_fkey   | (acquisition_id) REFERENCES acquisitions(id)
#  transferred_assets_cost_currency_id_fkey | (cost_currency_id) REFERENCES currencies(id)
#  transferred_assets_currency_id_fkey      | (currency_id) REFERENCES currencies(id)
#  transferred_assets_from_account_id_fkey  | (from_account_id) REFERENCES accounts(id)
#  transferred_assets_portfolio_id_fkey     | (portfolio_id) REFERENCES portfolios(id)
#  transferred_assets_to_account_id_fkey    | (to_account_id) REFERENCES accounts(id)
#  transferred_assets_transfer_id_fkey      | (transfer_id) REFERENCES transfers(id)

class TransferredAsset < Sequel::Model
  many_to_one :portfolio
  many_to_one :from_account, class: :Account
  many_to_one :to_account, class: :Account
  many_to_one :transfer, class: :Transfer
  many_to_one :currency
  many_to_one :cost_currency, class: :Currency
  many_to_one :acquisition, class: :Acquisition

  TABLE_HEADERS = [
    ' ', 'from', ' ', 'to',
    'id', 'transfer_id', 'type',
    'amount', '',
    'cost', '', 'cost_avg', '',
    'acc_cost', '', 'acc_cost_avg', '',
    'acquired', 'created'
  ].freeze
  TABLE_ALIGNMENTS = ((%i[right left] * 2) + (%i[left] * 3) + (%i[right left] * 3) + %i[left left]).freeze
  extend TableFormatter

  def table_row
    avg_currency_symbol = cost_currency ? "#{cost_currency.symbol}/#{currency.symbol}" : nil
    [
      from_account_id, from_account.name,
      to_account_id, to_account.name,
      id, transfer_id, acquisition_type,

      # amount,
      amount.to_s('F'), currency.symbol,
      # cost
      cost_amount&.round(2)&.to_s('F'), cost_currency&.symbol,
      average_cost_amount&.round(2)&.to_s('F'), avg_currency_symbol,
      account_cost_amount&.round(2)&.to_s('F'), cost_currency&.symbol,
      account_average_cost_amount&.round(2)&.to_s('F'), avg_currency_symbol,
      acquired_at.strftime('%Y-%m-%d %H:%M:%S'),
      created_at.strftime('%Y-%m-%d %H:%M:%S')
    ]
  end
end
