# frozen_string_literal: true

# Table: wallets
# Columns:
#  id          | integer                     | PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY
#  platform_id | integer                     | NOT NULL
#  currency_id | integer                     | NOT NULL
#  address     | text                        | NOT NULL
#  created_at  | timestamp without time zone | NOT NULL
#  updated_at  | timestamp without time zone | NOT NULL
# Indexes:
#  wallets_pkey                                  | PRIMARY KEY btree (id)
#  wallets_platform_id_currency_id_address_index | UNIQUE btree (platform_id, currency_id, address)
#  wallets_address_index                         | btree (address)
#  wallets_created_at_index                      | btree (created_at)
#  wallets_currency_id_address_index             | btree (currency_id, address)
#  wallets_updated_at_index                      | btree (updated_at)
# Foreign key constraints:
#  wallets_currency_id_fkey | (currency_id) REFERENCES currencies(id)
#  wallets_platform_id_fkey | (platform_id) REFERENCES platforms(id)
# Referenced By:
#  account_wallets | account_wallets_wallet_id_fkey | (wallet_id) REFERENCES wallets(id)

class Wallet < Sequel::Model
  one_to_one :platform
  one_to_one :currency
end
